<MyRoot>:
<RelativeLayout>:
    Spinner:
        size_hint: None, None
        size: 120, 44
        pos_hint: {'center': (.5, .5)}
        text: 'Home'
        values: 'Home', 'Work', 'Other', 'Custom'
        on_value: 
        print: "The spinner {} has text {}".format(self, self.values)
#    Button:
#	    text: 'Start'
#		size_hint_y: None
#		size: 120, 44
#		on_release: root.select('item1') 
